safe: true
baseurl: /
url: http://localhost:4000
# Timezone configuration
timezone: Asia/Tehran

highlighter: true
markdown: kramdown
permalink: date
maruku:
    use_tex:    false
    use_divs:   false
    png_engine: blahtex
    png_dir:    images/latex
    png_url:    /images/latex
